version: '3.0'
services:
  my-api:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
    volumes:
      - logfile:/src/log/logDocerApp
    networks:
      - connect-network
    restart: on-failure

  db-postgres:
    build: .database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - logfile:/src/log/logDocerDB
    networks:
      - connect-network
    restart: on-failure

networks:
  connect-network:
    driver: bridge

volumes:
  logfile:
